const FINANCE_ERROR_KEYS = {
  Unauthorized: "common.errors.unauthorized",
  "Mutation access requires an active Moniq subscription.": "common.errors.billing.subscriptionRequired",
  "Unable to load finance data.": "common.errors.finance.load",
  "Unable to load exchange rates.": "common.errors.fx.load",
  "Unable to save exchange rates.": "common.errors.fx.save",
  "Unable to create wallet.": "common.errors.wallet.create",
  "Unable to update wallet.": "common.errors.wallet.update",
  "Unable to delete wallet.": "common.errors.wallet.delete",
  "Unable to update settings.": "common.errors.settings.preferencesUpdate",
  "Unable to create category.": "common.errors.category.create",
  "Unable to update category.": "common.errors.category.update",
  "Unable to delete category.": "common.errors.category.delete",
  "Unable to create transaction.": "common.errors.transaction.create",
  "Unable to update transaction.": "common.errors.transaction.update",
  "Unable to delete transaction.": "common.errors.transaction.delete",
  "Unable to load imported transactions.": "common.errors.imports.load",
  "Unable to update imported transaction.": "common.errors.imports.update",
  "Unable to confirm imported transaction.": "common.errors.imports.confirm",
  "Unable to delete import batch.": "common.errors.imports.delete",
  "Unable to delete imported transaction.": "common.errors.imports.deleteTransaction",
  "Wallet not found.": "common.errors.imports.walletNotFound",
  "Choose the debt account for this payment.": "common.errors.imports.debtWalletRequired",
  "Choose a different debt account for this payment.": "common.errors.imports.debtWalletDifferentRequired",
  "Choose a different destination wallet for this transfer.": "common.errors.imports.transferWalletDifferentRequired",
  "Imported transaction not found.": "common.errors.imports.transactionNotFound",
  "Import batch not found.": "common.errors.imports.batchNotFound",
  "Only draft imported transactions can be deleted.": "common.errors.imports.transactionDeleteDraftOnly",
  "Choose a CSV file to import.": "common.errors.imports.fileRequired",
  "Choose a wallet before importing.": "common.errors.imports.walletRequired",
  "CSV file is empty.": "common.errors.imports.emptyFile",
  "CSV headers are missing.": "common.errors.imports.invalidFile",
  "CSV file did not contain recognizable transaction rows.": "common.errors.imports.invalidFile",
  "Category not found.": "common.errors.category.notFound",
  "Choose a replacement category before deleting this category.": "common.errors.category.replacementRequired",
  "Replacement category not found.": "common.errors.category.replacementNotFound",
  "Replacement category must be different.": "common.errors.category.replacementDifferent",
  "Replacement category must have the same type.": "common.errors.category.replacementSameType",
  "Transaction not found.": "common.errors.transaction.notFound",
  "Transaction schedule not found.": "common.errors.transaction.scheduleNotFound",
  "Parent category not found.": "common.errors.category.parentNotFound",
  "Parent category must have the same type.": "common.errors.category.parentSameType",
  "A category cannot be its own parent.": "common.errors.category.cannotBeOwnParent",
  "A category cannot be moved under its own descendant.": "common.errors.category.cannotMoveUnderDescendant",
  "System categories cannot be edited.": "common.errors.category.systemEdit",
  "System categories cannot be deleted.": "common.errors.category.systemDelete",
  "The investment category must remain an expense category.": "common.errors.category.investmentType",
  "The investment category cannot be deleted.": "common.errors.category.investmentDelete",
  "Source account not found.": "common.errors.transaction.sourceNotFound",
  "Destination account not found.": "common.errors.transaction.destinationNotFound",
  "Choose a category with the matching type.": "common.errors.transaction.categoryTypeMismatch",
  "Debt payment interest can only use an expense category.": "common.errors.transaction.debtCategoryExpenseOnly",
  "Debt payment must target a debt or credit card account.": "common.errors.transaction.debtNeedsDebtAccount",
  "Transfers do not use categories.": "common.errors.transaction.transferNoCategory",
  "Investment purchases must use the investment category.": "common.errors.transaction.investmentCategory",
  "Investment purchases must use an ETF position.": "common.errors.transaction.investmentEtf",
  "Investment position not found.": "common.errors.transaction.investmentNotFound",
  "Unable to search investments.": "common.errors.investment.search",
  "Unable to save investment instrument.": "common.errors.investment.save",
  "Unable to save investment.": "common.errors.investment.save",
  "Supabase schema is out of date. Run `npx supabase db push` and reload the app.":
    "common.errors.finance.schemaOutOfDate",
} as const;

type FinanceErrorMessage = keyof typeof FINANCE_ERROR_KEYS;

export function translateFinanceErrorMessage(t: (key: string) => string, message: string) {
  const key = FINANCE_ERROR_KEYS[message as FinanceErrorMessage];
  return key ? t(key) : message;
}
