import fs from "node:fs";
import path from "node:path";

const enJsonPath = path.resolve("messages/en.json");
const dtsPath = path.resolve("messages/en.d.json.ts");

const enJson = JSON.parse(fs.readFileSync(enJsonPath, "utf8"));

function formatObject(obj, indent = 2) {
  const spaces = " ".repeat(indent);
  if (typeof obj === "string") {
    return JSON.stringify(obj);
  }
  if (Array.isArray(obj)) {
    return (
      "[\n" +
      obj.map((item) => spaces + "  " + formatObject(item, indent + 2)).join(",\n") +
      "\n" +
      spaces +
      "]"
    );
  }
  const keys = Object.keys(obj);
  const lines = keys.map((key) => {
    const val = obj[key];
    const keyStr = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
    return `${spaces}${keyStr}: ${formatObject(val, indent + 2)}`;
  });
  return "{\n" + lines.join(",\n") + "\n" + " ".repeat(indent - 2) + "}";
}

const content = `// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: ${formatObject(enJson)};
export default messages;
`;

fs.writeFileSync(dtsPath, content, "utf8");
console.log("Successfully generated messages/en.d.json.ts");
